In [1]:
import numpy as np

In [2]:
m1 = np.array([[1,2,3],[4,5,6]])
m1
              

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
m1.ndim,m1.shape

(2, (2, 3))

In [6]:
m2 = np.array([[10,11,12],[13,14,15]])
m2

array([[10, 11, 12],
       [13, 14, 15]])

In [7]:
m2.shape,m2.ndim

((2, 3), 2)

In [14]:
m1+m2,m1-m2,m1*m2,m1/m2,m1//m2,m1**m2

(array([[11, 13, 15],
        [17, 19, 21]]),
 array([[-9, -9, -9],
        [-9, -9, -9]]),
 array([[10, 22, 36],
        [52, 70, 90]]),
 array([[0.1       , 0.18181818, 0.25      ],
        [0.30769231, 0.35714286, 0.4       ]]),
 array([[0, 0, 0],
        [0, 0, 0]]),
 array([[         1,       2048,     531441],
        [  67108864, 1808548329, 2033549312]]))

In [16]:
m1.ndim,m1.shape,m1.dtype,m1.itemsize

(2, (2, 3), dtype('int32'), 4)

In [17]:
m1.dot(m2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [20]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
m2 = np.array([[10,11],[12,13],[14,15]])
m2

array([[10, 11],
       [12, 13],
       [14, 15]])

In [19]:
m1.dot(m2)

array([[ 76,  82],
       [184, 199]])

In [21]:
m2.dot(m1)

array([[ 54,  75,  96],
       [ 64,  89, 114],
       [ 74, 103, 132]])

In [25]:
m1%m2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [29]:
m1  = m1.transpose()

In [34]:
m1 = np.arange(10)
type(m1),m1.shape,m1.ndim

(numpy.ndarray, (10,), 1)

In [35]:
m2 = np.arange(1,10)
m2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
m3 = np.arange(1,51,2)
m3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [47]:
m4 = np.linspace(1,10,19)
m4

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [50]:
m4 = np.linspace(1,20)
m4.shape

(50,)

In [45]:
(10-1)/(50-1)

0.1836734693877551

In [51]:
np.linspace(1,10,20,endpoint=True)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [56]:
m4 = np.linspace(1,20,20,endpoint=False)
m4

array([ 1.  ,  1.95,  2.9 ,  3.85,  4.8 ,  5.75,  6.7 ,  7.65,  8.6 ,
        9.55, 10.5 , 11.45, 12.4 , 13.35, 14.3 , 15.25, 16.2 , 17.15,
       18.1 , 19.05])

In [57]:
m4 = np.linspace(1,20,20,endpoint=True)
m4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [62]:
m4 = np.linspace(1,20,2,endpoint=True)
m4

array([ 1., 20.])

In [54]:
(10-1)/(20-1)

0.47368421052631576