In [15]:
import numpy as np
l1 = [1,2,3]
a = np.array(l1)
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)

[1 2 3]
1
(3,)
int64
8


In [1]:
import numpy as np
a = [[1,2,3],[4,5,6],[7,8,9]]
my_array = np.array(a)
print("Array : \n",my_array)
print("Dimention of array: \n", my_array.ndim)
print("Shape of array: \n", my_array.shape)
print("Data types of array: \n", my_array.dtype)
print("Item size of array: \n",my_array.itemsize)
print(a*2)

Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimention of array: 
 2
Shape of array: 
 (3, 3)
Data types of array: 
 int64
Item size of array: 
 8
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]
