In [19]:
import numpy as np

a = [1,2,3,4,5,6]
new_array = np.array(a)
print('*'*30)

print('New Array: ',new_array)
print('Data Type Of Array: ',new_array.dtype)
print('Dimention Of Array: ',new_array.ndim)
print('Shape Of Array: ',new_array.shape)
print('Size Of Array: ',new_array.size)
print('Item Size Of Array: ',new_array.itemsize)

print('*'*30)

******************************
New Array:  [1 2 3 4 5 6]
Data Type Of Array:  int64
Dimention Of Array:  1
Shape Of Array:  (6,)
Size Of Array:  6
Item Size Of Array:  8
******************************


In [35]:
import numpy as np
subjects = ['math', 'hindi','english', 'physics', 'chemistry']
marks = [87,54,39,56,56]
details = np.array([subjects,marks])
print('Details Array: \n',details)
print('Data type of array: ',details.dtype)
print('Size of array: ',details.size)
print('Shape of array: ',details.shape)
print('Dimention of array: ',details.ndim)
print('Item Size of array: ',details.itemsize)

Details Array: 
 [['math' 'hindi' 'english' 'physics' 'chemistry']
 ['87' '54' '39' '56' '56']]
Data type of array:  <U21
Size of array:  10
Shape of array:  (2, 5)
Dimention of array:  2
Item Size of array:  84


In [47]:
import numpy as np
m1 = np.array([[1,2,3,4],[4,3,2,1]])
m2 = np.array([[10,20,30,40],[40,30,20,10]])
print('array 1\n\n',m1)
print()
print('array 2\n\n',m2)
print()
print('m1*m2 \n\n',m1*m2)

print('dot',m1.dot(m2.transpose()))



array 1

 [[1 2 3 4]
 [4 3 2 1]]

array 2

 [[10 20 30 40]
 [40 30 20 10]]

m1*m2 

 [[ 10  40  90 160]
 [160  90  40  10]]
dot [[300 200]
 [200 300]]


In [49]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
dot_product = a.dot(b)
print('dot_product',dot_product)

dot_product [[ 7 10]
 [15 22]]


In [51]:
a = np.array([[1,3],[2,4]])
b = np.array([[10,30],[20,40]])
print('MATRIX MULTIPLICATION')
print(a*b)
print('MATRIX DOT PRODUCDT')
print(a.dot(b))

MATRIX MULTIPLICATION
[[ 10  90]
 [ 40 160]]
MATRIX DOT PRODUCDT
[[ 70 150]
 [100 220]]
