In [10]:
import array

In [28]:
a = array.array('i',[10,20,30,40,50,-50])
type(a),a

(array.array, array('i', [10, 20, 30, 40, 50, -50]))

In [29]:
a+a

array('i', [10, 20, 30, 40, 50, -50, 10, 20, 30, 40, 50, -50])

In [13]:
a.append(60)
a

array('i', [10, 20, 30, 40, 50, -50, 60])

In [14]:
a.reverse()
a

array('i', [60, -50, 50, 40, 30, 20, 10])

In [15]:
a.pop()

10

In [17]:
a,len(a)

(array('i', [60, -50, 50, 40, 30, 20]), 6)

In [18]:
a.remove(60)
a

array('i', [-50, 50, 40, 30, 20])

In [19]:
x=[10,20,30,40,50]
x

[10, 20, 30, 40, 50]

In [20]:
x.append(60.65)
x

[10, 20, 30, 40, 50, 60.65]

In [21]:
a.append(60.45)

TypeError: 'float' object cannot be interpreted as an integer

In [24]:
x**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [25]:
import numpy as np

In [27]:
maths = np.array([86,80,91,94,85])
physics = np.array([80,89,78,93,96])
chemistry = np.array([84,94,92,90,91])

maths,physics,chemistry

(array([86, 80, 91, 94, 85]),
 array([80, 89, 78, 93, 96]),
 array([84, 94, 92, 90, 91]))

In [30]:
total = maths+physics+chemistry
total

array([250, 263, 261, 277, 272])

In [31]:
maths**2

array([7396, 6400, 8281, 8836, 7225])

In [33]:
np.log10(maths),np.log2(maths),np.log(maths)

(array([1.93449845, 1.90308999, 1.95904139, 1.97312785, 1.92941893]),
 array([6.42626475, 6.32192809, 6.50779464, 6.55458885, 6.40939094]),
 array([4.4543473 , 4.38202663, 4.51085951, 4.54329478, 4.44265126]))

In [37]:
angles = np.array([0,30,45,60,90])
np.sin(np.radians(angles)),np.cos(np.radians(angles))

(array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ]),
 array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
        6.12323400e-17]))

In [38]:
np.sqrt(physics)

array([8.94427191, 9.43398113, 8.83176087, 9.64365076, 9.79795897])