In [1]:
import numpy as np


In [2]:
x = np.array([10,20,30,40,50])
type(x)

numpy.ndarray

In [4]:
x+10,x-10,x*10,x/3,x//3,x%3,x**3

(array([20, 30, 40, 50, 60]),
 array([ 0, 10, 20, 30, 40]),
 array([100, 200, 300, 400, 500]),
 array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667]),
 array([ 3,  6, 10, 13, 16], dtype=int32),
 array([1, 2, 0, 1, 2], dtype=int32),
 array([  1000,   8000,  27000,  64000, 125000], dtype=int32))

In [12]:
np.log10(x),np.log(x),np.sqrt(x)

(array([1.        , 1.30103   , 1.47712125, 1.60205999, 1.69897   ]),
 array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301]),
 array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781]))

In [21]:
x=np.array([10,20,30,40.5,50],dtype='int32')
x

array([10, 20, 30, 40, 50])

In [22]:
x.ndim,x.shape,x.dtype,x.itemsize

(1, (5,), dtype('int32'), 4)

In [28]:
maths = np.array([83,80,94,90,85])
physics = np.array([85,80,82,95,91])
chemistry = np.array([85,80,75,84,95])
maths.ndim,maths.shape

(1, (5,))

In [27]:
marks  = np.array([[83,80,94,90,85],[85,80,82,95,91],[85,80,75,84,95]])
marks

array([[83, 80, 94, 90, 85],
       [85, 80, 82, 95, 91],
       [85, 80, 75, 84, 95]])

In [30]:
marks.shape,marks.ndim

((3, 5), 2)

In [31]:
#create a 5,3 dimmension array 

y= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [35]:
y.ndim,y.shape,y.dtype,y.itemsize

(2, (5, 3), dtype('int32'), 4)

In [41]:
z = np.array([[56,45,23,12,67,60],[70,80,34,55,66,77]])
z

array([[56, 45, 23, 12, 67, 60],
       [70, 80, 34, 55, 66, 77]])

In [42]:
z.shape

(2, 6)