In [1]:
import numpy  as np

In [2]:
x = np.arange(1,50,3)
x

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [4]:
y = np.linspace(1,49,16,endpoint=False)
y

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
       40., 43., 46.])

In [7]:
x = np.arange(1,13)
x.shape,x.ndim

((12,), 1)

In [9]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
x1 = x.reshape(4,3)
x1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
x2 = x1.reshape(3,4)
x2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
x3 = x2.reshape(6,2)
x3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
x4= x2.reshape(2,6)
x4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [21]:
x5 = np.arange(52,76).reshape(8,3)
x5

array([[52, 53, 54],
       [55, 56, 57],
       [58, 59, 60],
       [61, 62, 63],
       [64, 65, 66],
       [67, 68, 69],
       [70, 71, 72],
       [73, 74, 75]])

In [30]:
x6 = np.linspace(50,100,24).reshape(12,2)
x6

array([[ 50.        ,  52.17391304],
       [ 54.34782609,  56.52173913],
       [ 58.69565217,  60.86956522],
       [ 63.04347826,  65.2173913 ],
       [ 67.39130435,  69.56521739],
       [ 71.73913043,  73.91304348],
       [ 76.08695652,  78.26086957],
       [ 80.43478261,  82.60869565],
       [ 84.7826087 ,  86.95652174],
       [ 89.13043478,  91.30434783],
       [ 93.47826087,  95.65217391],
       [ 97.82608696, 100.        ]])

In [49]:
x=np.array([[80,89,60,78,90],[65,79,90,82,88],[90,92,94,91,85]])
x.shape,x.ndim

((3, 5), 2)

In [55]:
x=x.reshape(5,3)
x

array([[80, 89, 60],
       [78, 90, 65],
       [79, 90, 82],
       [88, 90, 92],
       [94, 91, 85]])

In [43]:
x.shape,x.ndim

((5, 3), 2)

In [47]:
zero_array = np.zeros((10,10),dtype='int32')
zero_array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [59]:
zero_array = np.zeros_like(a)
zero_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
ones_array = np.ones((5,8),dtype='int32')*20
ones_array

array([[20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20]])

In [58]:
ones_array = np.ones_like(a)
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
a = np.linspace(1,10,50).reshape(10,5)
a

array([[ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388],
       [ 1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122],
       [ 2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857],
       [ 3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592],
       [ 4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327],
       [ 5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061],
       [ 6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796],
       [ 7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531],
       [ 8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265],
       [ 9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]])

In [68]:
np.linspace(1,10,10,dtype='int32')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
I = np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])