In [1]:
import numpy as np

In [58]:
x = np.random.random_sample((6,3))
x

array([[0.75993539, 0.74937377, 0.1550422 ],
       [0.36644996, 0.86152083, 0.42766237],
       [0.82480761, 0.66348944, 0.57322432],
       [0.07358198, 0.69749837, 0.51141519],
       [0.16202535, 0.46463942, 0.36858279],
       [0.98048253, 0.05409541, 0.70169123]])

In [79]:
marks = np.random.randint(75,96,(5,6))
marks

array([[90, 91, 78, 89, 95, 85],
       [86, 80, 88, 94, 88, 93],
       [80, 88, 84, 91, 76, 81],
       [90, 78, 91, 88, 76, 94],
       [84, 90, 84, 89, 86, 77]])

In [54]:
m1 = np.random.randint(1,16,(3,5))
m1

array([[ 9, 12,  7, 10, 12],
       [10, 10, 13,  7,  5],
       [ 5,  7,  3,  1, 14]])

In [55]:
m2 = np.random.randint(20,35,(5,4))
m2

array([[26, 27, 21, 24],
       [34, 30, 32, 34],
       [24, 32, 26, 27],
       [23, 30, 29, 24],
       [26, 20, 33, 28]])

In [56]:
m1.dot(m2)

array([[1352, 1367, 1441, 1389],
       [1203, 1296, 1236, 1239],
       [ 827,  751,  898,  855]])

In [174]:
100*np.random.random_sample((10,4))+100

array([[110.79575965, 192.44748944, 175.00753215, 188.51963166],
       [114.77689648, 160.6499609 , 109.71754355, 146.47013683],
       [141.1679149 , 187.73454796, 191.11322532, 115.27739109],
       [189.82288524, 106.95491023, 166.4699903 , 193.22627728],
       [113.32015005, 195.31846615, 121.79583343, 160.20988545],
       [107.67165014, 141.92718521, 182.51136861, 159.16522175],
       [188.88058814, 154.82444265, 198.36461046, 125.24562754],
       [140.89653845, 129.74416674, 121.20359378, 170.82016477],
       [163.80407361, 198.90725647, 178.26343651, 104.99282225],
       [165.47567493, 158.33471598, 102.36437562, 133.53935007]])

In [226]:
np.random.seed(0)
np.random.randint(10,20,10)

array([15, 10, 13, 13, 17, 19, 13, 15, 12, 14])

In [233]:
np.random.seed(0)
np.random.randint(10,20,10)

array([15, 10, 13, 13, 17, 19, 13, 15, 12, 14])